# Generated by Django 6.0.7 on 2026-07-16 09:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_updated_at_alter_employee_status'),
        ('workorders', '0002_alter_workorder_work_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(default=django.utils.timezone.now)),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5)),
                ('work_performed', models.TextField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='workorders.workorder')),
            ],
            options={
                'ordering': ['-maintenance_date'],
            },
        ),
    ]
