# Generated by Django 6.0.7 on 2026-07-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='work_order_number',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True),
        ),
    ]
